Style & functionality changes
* Use lowercase variables
* Print usage if --help is given anywhere on the command line
* Use ${0##*/} instead of $(basename $0)
* Use quotes when needed
* Don't put `then` or `do` on their own line
* Use tab to indent the bodies of case statements
* Escape quotes the proper number of times in sshdiff
* Remove useless function in wscrot

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -4,18 +4,18 @@
 # adapted from https://wiki.archlinux.org/index.php/Bash#Functions
 
 retval=0
-PROG="$(basename "$0")"
+prog="${0##*/}"
 
 extensions() {
 	sed -rn '/\*\..*\)/ {
 		s/^[^*]*\*\.|\).*$//g
 		s/\|(\*\.)/\n/
 		p
-	}' $0
+	}' "$0"
 }
 
 usage() {
-	echo "Usage: $PROG file1 [ file2 ... ]
+	echo "Usage: $prog file1 [ file2 ... ]
 
     Extract an archive.
 
@@ -23,37 +23,36 @@ usage() {
 "
 }
 
-case "$1" in ""|"-h"|"--help")
+if [[ "$*" =~ (^| )("-h"|"--help")( |$) || $# == 0 ]]; then
 	usage
 	exit
-esac
+fi
 
-for file in "$@"
-do
+for file in "$@"; do
 	if [[ -f "$file" ]]; then
 		case "$file" in
-		  *.tar.bz2|*.tbz2)
-		         tar xvjf   "$file" ;;
-		  *.tar.gz|*.tgz)
-		         tar xvzf   "$file" ;;
-		  *.tar.xz|*.txz)
-		         tar xvJf   "$file" ;;
-		  *.tar) tar xvf    "$file" ;;
-		  *.7z)  7z x       "$file" ;;
-		  *.Z)   uncompress "$file" ;;
-		  *.bz2) bunzip2    "$file" ;;
-		  *.exe) cabextract "$file" ;;
-		  *.gz)  gunzip     "$file" ;;
-		  *.rar) unrar x    "$file" ;;
-		  *.xz)  unxz       "$file" ;;
-		  *.zip) unzip      "$file" ;;
-		  *.jar) jar xvf    "$file" ;;
-		  *.rpm) rpm2cpio   "$file" | cpio -idmv ;;
-		  *)     echo "$PROG: $file: unknown extension" >&2
-		         retval=1 ;;
+			*.tar.bz2|*.tbz2)
+			       tar xvjf   "$file" ;;
+			*.tar.gz|*.tgz)
+			       tar xvzf   "$file" ;;
+			*.tar.xz|*.txz)
+			       tar xvJf   "$file" ;;
+			*.tar) tar xvf    "$file" ;;
+			*.7z)  7z x       "$file" ;;
+			*.Z)   uncompress "$file" ;;
+			*.bz2) bunzip2    "$file" ;;
+			*.exe) cabextract "$file" ;;
+			*.gz)  gunzip     "$file" ;;
+			*.rar) unrar x    "$file" ;;
+			*.xz)  unxz       "$file" ;;
+			*.zip) unzip      "$file" ;;
+			*.jar) jar xvf    "$file" ;;
+			*.rpm) rpm2cpio   "$file" | cpio -idmv ;;
+			*)     echo "$prog: $file: unknown extension" >&2
+			       retval=1 ;;
 		esac
 	else
-	    echo "$PROG: $file: file not found" >&2
+	    echo "$prog: $file: file not found" >&2
 	    retval=2
 	fi
 done
